/**
 * `FileStoragePort` (foundation R3.23, OD-12; sige/02 §2.2). v1 stores only the institution logo.
 * Adapters: local disk (dev/test, served by a static route in `apps/server`) and an S3-compatible
 * one for production. Keys are generated by the caller, never taken from user input.
 */
export interface FileStoragePort {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<{ url: string }>;
  /** Deleting a missing object is not an error. */
  delete(key: string): Promise<void>;
}
