import {
  ASSIGNMENT_OFFERING_FK,
  ASSIGNMENT_OFFERING_UNIQUE,
  CAMPUS_CODE_UNIQUE,
  CLASSROOM_CAMPUS_FK,
  CLASSROOM_CODE_UNIQUE,
  CAMPUS_MAIN_UNIQUE,
  COURSE_CAMPUS_FK,
  COURSE_DIRECTOR_FK,
  COURSE_LEVEL_CAMPUS_FK,
  COURSE_UNIQUE,
  ENROLLMENT_FINAL_SCORE_CHECK,
  ENROLLMENT_OFFERING_FK,
  ENROLLMENT_STATUS_NOTE_CHECK,
  ENROLLMENT_STUDENT_FK,
  ENROLLMENT_UNIQUE,
  GUARDIAN_LINK_UNIQUE,
  GUARDIAN_PERSON_FK,
  GUARDIAN_STUDENT_FK,
  IMPORT_JOB_CREATOR_FK,
  IMPORT_JOB_RUNNING_UNIQUE,
  INSTITUTION_NIT_UNIQUE,
  LEVEL_CAMPUS_FK,
  LEVEL_NAME_UNIQUE,
  OFFERING_COURSE_FK,
  OFFERING_SUBJECT_FK,
  OFFERING_TEACHER_FK,
  OFFERING_UNIQUE,
  PERIOD_ACTIVE_UNIQUE,
  PERIOD_ORDER_UNIQUE,
  PERIOD_SHORT_NAME_UNIQUE,
  PERSON_DOCUMENT_UNIQUE,
  SLOT_CLASSROOM_EXCLUDE,
  SLOT_CLASSROOM_FK,
  SLOT_COURSE_EXCLUDE,
  SLOT_TEACHER_EXCLUDE,
  STUDENT_CAMPUS_FK,
  STUDENT_COURSE_CAMPUS_FK,
  STUDENT_PERSON_FK,
  STUDENT_PERSON_UNIQUE,
  STUDENT_STRATUM_CHECK,
  SUBJECT_CODE_UNIQUE,
  TIME_BLOCK_CAMPUS_FK,
  TIME_BLOCK_UNIQUE,
} from "@base-template/db/schema";
import { ORPCError } from "@orpc/server";

/**
 * Postgres error -> oRPC error mapper for SIGE services (sige/02 §4.1, §4.2; foundation R3.5).
 * Constraints are the arbiter, never a racy pre-check: a service writes, catches the violation and
 * maps it by SQLSTATE plus constraint name to the Spanish spec message.
 *
 * - `23505` unique_violation -> `CONFLICT` (409), message per constraint.
 * - `23001` restrict_violation / `23503` foreign_key_violation on **delete** -> `HAS_DEPENDENTS`
 *   (409). `ON DELETE RESTRICT` raises 23001; 23503 covers `NO ACTION` FKs added by later modules.
 * - `23P01` exclusion_violation (schedule double-booking, SCH-R9) -> `CONFLICT` (409).
 * - `23514` check_violation on a user-entered field -> `BAD_REQUEST`; checks on server-set values
 *   (years, teacher sync) stay unmapped because they signal a service bug.
 * - `23503` on **insert/update** -> `BAD_REQUEST` or `NOT_FOUND` (a referenced row is missing).
 * Anything else is left to the caller (rethrown unchanged).
 */

export type DbOperation = "write" | "delete";

const SQLSTATE_UNIQUE_VIOLATION = "23505";
const SQLSTATE_RESTRICT_VIOLATION = "23001";
const SQLSTATE_FOREIGN_KEY_VIOLATION = "23503";
const SQLSTATE_EXCLUSION_VIOLATION = "23P01";
const SQLSTATE_CHECK_VIOLATION = "23514";

/** Declared next to the other SIGE codes (foundation R3.5); the web maps it to a toast. */
export const HAS_DEPENDENTS = "HAS_DEPENDENTS";
const CONFLICT_STATUS = 409;

/** better-auth `user` constraint names generated by drizzle-kit (see provision-user.ts). */
const USER_EMAIL_UNIQUE = "user_email_key";
const USER_USERNAME_UNIQUE = "user_username_key";

const UNIQUE_MESSAGES: Record<string, string> = {
  [PERSON_DOCUMENT_UNIQUE]: "Ya existe un usuario con este documento.",
  [USER_EMAIL_UNIQUE]: "Ya existe un usuario con este correo.",
  // Not in spec §4.1 (writer-authored).
  [USER_USERNAME_UNIQUE]: "Ya existe un usuario con este nombre de usuario.",
  [CAMPUS_MAIN_UNIQUE]: "Ya existe una sede principal en esta institución.",
  [CAMPUS_CODE_UNIQUE]: "Ya existe una sede con este código.",
  [LEVEL_NAME_UNIQUE]: "Ya existe un nivel con este nombre en la sede.",
  [COURSE_UNIQUE]: "Ya existe un grado con la misma sede, nombre, año y jornada.",
  [SUBJECT_CODE_UNIQUE]: "Ya existe una asignatura con este código.",
  [INSTITUTION_NIT_UNIQUE]: "Ya existe una institución con este NIT.",
  // USR-R12: one running import per institution and kind (D7).
  [IMPORT_JOB_RUNNING_UNIQUE]: "Ya hay una importación en curso.",
  // Not in spec §4.1 (writer-authored).
  [PERIOD_ACTIVE_UNIQUE]: "Ya existe un periodo activo en esta institución.",
  [PERIOD_SHORT_NAME_UNIQUE]: "Ya existe un periodo con este nombre corto en el año.",
  [PERIOD_ORDER_UNIQUE]: "Ya existe un periodo con este orden en el año.",
  // sige/04 §4.1.
  [CLASSROOM_CODE_UNIQUE]: "Ya existe un salón con este código en la sede.",
  [TIME_BLOCK_UNIQUE]: "Ya existe un bloque con este nombre en la sede y jornada.",
  // Not in spec §4.1 (writer-authored).
  [OFFERING_UNIQUE]: "La materia ya está asignada a este grado.",
  [ASSIGNMENT_OFFERING_UNIQUE]: "La materia del grado ya tiene una asignación.",
  // sige/05 STU-R8 copy: the person (found by document) already has an academic profile.
  [STUDENT_PERSON_UNIQUE]: "Ya existe un estudiante con este documento.",
  // sige/05 STU-R6.
  [GUARDIAN_LINK_UNIQUE]: "Este acudiente ya está vinculado a este estudiante.",
  // Not in spec (writer-authored); bulk enrollment skips existing rows, so this is a race only.
  [ENROLLMENT_UNIQUE]: "El estudiante ya está matriculado en esta materia.",
};

/** 23514 on user-entered fields, keyed by check constraint (sige/05 §4.1, sige/04 §4.1). */
const CHECK_MESSAGES: Record<string, string> = {
  [STUDENT_STRATUM_CHECK]: "El estrato debe estar entre 1 y 6.",
  [ENROLLMENT_FINAL_SCORE_CHECK]: "La nota final debe estar entre 1.0 y 5.0.",
  // Same copy as the zod schema (`schemas/enrollment.ts`).
  [ENROLLMENT_STATUS_NOTE_CHECK]: "No puede superar 500 caracteres.",
};

/**
 * SCH-R9 double-booking (23P01), keyed by exclusion constraint. Only the teacher text is in the
 * spec (SCH-R3: "... ({curso}, {día} {hora})."); the DB error cannot name the clashing course,
 * day and hour, so the generic form without the parenthesis is used until a service that has the
 * clashing slot at hand composes the full message. Classroom and course texts are writer-authored
 * by analogy (the spec states no exact copy for them).
 */
const EXCLUSION_MESSAGES: Record<string, string> = {
  [SLOT_TEACHER_EXCLUDE]: "El profesor ya tiene clases en el mismo horario.",
  [SLOT_CLASSROOM_EXCLUDE]: "El salón ya está ocupado en el mismo horario.",
  [SLOT_COURSE_EXCLUDE]: "El grado ya tiene clases en el mismo horario.",
};

/**
 * HAS_DEPENDENTS copy that no FK can raise on its own, exported for the services (T4/T5) that
 * pre-check it inside the delete transaction: a slot cascades from its offering, and a block is
 * "in use" by start and end time rather than by an FK (sige/04 §4.2).
 */
export const OFFERING_HAS_SLOTS_MESSAGE =
  "La materia del grado tiene clases programadas en el horario.";
export const TIME_BLOCK_IN_USE_MESSAGE = "El bloque tiene clases programadas en el horario.";

/**
 * Copy for deletes blocked by more than one kind of dependent, where the FK Postgres reports
 * first is not the one the spec lists first (sige/02 §4.2, sige/04 §4.2, sige/05 STU-R7). The
 * services pre-check inside the delete transaction to keep the spec order; the FK map below stays
 * the arbiter for races.
 */
export const OFFERING_HAS_ENROLLMENTS_MESSAGE =
  "La materia del grado tiene estudiantes matriculados.";
export const CAMPUS_HAS_STUDENTS_MESSAGE = "La sede tiene estudiantes asociados.";
export const COURSE_HAS_STUDENTS_MESSAGE = "El grado tiene estudiantes asociados.";
export const STUDENT_HAS_RECORDS_MESSAGE =
  "El estudiante tiene matrículas, notas o asistencia registradas.";

/** Spec §4.2 messages, keyed by the `restrict` FK that fired (person FKs: see USR-R7 below). */
const DEPENDENTS_MESSAGES: Record<string, string> = {
  [LEVEL_CAMPUS_FK]: "La sede tiene niveles o grados asociados.",
  [COURSE_CAMPUS_FK]: "La sede tiene niveles o grados asociados.",
  [COURSE_LEVEL_CAMPUS_FK]: "El nivel tiene cursos asociados.",
  // sige/02 §4.2: a course or subject that still has offerings.
  [OFFERING_COURSE_FK]: "El grado tiene asignaturas asignadas.",
  [OFFERING_SUBJECT_FK]: "La asignatura está asignada a uno o más grados.",
  [OFFERING_TEACHER_FK]: "El profesor tiene asignaturas o grupos a cargo.",
  // sige/02 §4.2 (campus) and sige/04 §4.2 (classroom).
  [CLASSROOM_CAMPUS_FK]: "La sede tiene salones o bloques horarios asociados.",
  [TIME_BLOCK_CAMPUS_FK]: "La sede tiene salones o bloques horarios asociados.",
  [SLOT_CLASSROOM_FK]: "El salón tiene clases programadas en el horario.",
  // sige/04 §4.2 (P3 D2), sige/02 §4.2, sige/05 STU-R7.
  [ENROLLMENT_OFFERING_FK]: OFFERING_HAS_ENROLLMENTS_MESSAGE,
  [STUDENT_CAMPUS_FK]: CAMPUS_HAS_STUDENTS_MESSAGE,
  [STUDENT_COURSE_CAMPUS_FK]: COURSE_HAS_STUDENTS_MESSAGE,
  [ENROLLMENT_STUDENT_FK]: STUDENT_HAS_RECORDS_MESSAGE,
};
const DEPENDENTS_FALLBACK = "El registro tiene elementos asociados.";

/**
 * Spec sige/03 USR-R7: deleting a person that something still references. The message depends on
 * the person's role; the import-job creator link is "any other reference" for every role.
 */
const USER_DEPENDENTS_BY_ROLE: Record<string, string> = {
  teacher: "El profesor tiene asignaturas o grupos a cargo.",
  student: "El estudiante tiene un perfil académico con notas y matrículas.",
  parent: "El acudiente tiene estudiantes vinculados.",
};
const USER_DEPENDENTS_FALLBACK = "El usuario tiene registros asociados. Desactívelo en su lugar.";
const USER_DEPENDENTS_GENERIC_FKS = new Set<string>([IMPORT_JOB_CREATOR_FK]);
/** FKs onto `person` that name the dependent themselves, whatever role the person holds now. */
const USER_DEPENDENTS_BY_FK: Record<string, string> = {
  [STUDENT_PERSON_FK]: USER_DEPENDENTS_BY_ROLE.student!,
  [GUARDIAN_PERSON_FK]: USER_DEPENDENTS_BY_ROLE.parent!,
};

function userDependentsMessage(role: string, constraint: string): string {
  if (USER_DEPENDENTS_GENERIC_FKS.has(constraint)) return USER_DEPENDENTS_FALLBACK;
  return (
    USER_DEPENDENTS_BY_FK[constraint] ?? USER_DEPENDENTS_BY_ROLE[role] ?? USER_DEPENDENTS_FALLBACK
  );
}

export type DbErrorOptions = {
  /** Deleting a person: picks the role-specific HAS_DEPENDENTS message (USR-R7). */
  personRole?: string;
};

type FkWriteRule = { code: "BAD_REQUEST" | "NOT_FOUND"; message: string };

const FK_WRITE_RULES: Record<string, FkWriteRule> = {
  [COURSE_LEVEL_CAMPUS_FK]: {
    code: "BAD_REQUEST",
    message: "El nivel no pertenece a la sede seleccionada.",
  },
  [LEVEL_CAMPUS_FK]: { code: "NOT_FOUND", message: "La sede no existe." },
  [COURSE_CAMPUS_FK]: { code: "NOT_FOUND", message: "La sede no existe." },
  [COURSE_DIRECTOR_FK]: {
    code: "BAD_REQUEST",
    message: "El director debe ser un profesor activo de la institución.",
  },
  // Writer-authored (sige/04 §4.1 only covers the client-side "Debes seleccionar ..." copy).
  [CLASSROOM_CAMPUS_FK]: { code: "NOT_FOUND", message: "La sede no existe." },
  [TIME_BLOCK_CAMPUS_FK]: { code: "NOT_FOUND", message: "La sede no existe." },
  [OFFERING_SUBJECT_FK]: { code: "NOT_FOUND", message: "La materia no existe." },
  [OFFERING_COURSE_FK]: { code: "NOT_FOUND", message: "El grado no existe." },
  [OFFERING_TEACHER_FK]: { code: "NOT_FOUND", message: "El profesor no existe." },
  [SLOT_CLASSROOM_FK]: { code: "NOT_FOUND", message: "El salón no existe." },
  [ASSIGNMENT_OFFERING_FK]: {
    code: "BAD_REQUEST",
    message: "La asignación debe corresponder a la materia del grado y a su profesor.",
  },
  // sige/05 §4.1: the (campus, course) pair must exist, i.e. the course belongs to the campus.
  [STUDENT_COURSE_CAMPUS_FK]: {
    code: "BAD_REQUEST",
    message: "El grado no pertenece a la sede seleccionada.",
  },
  [STUDENT_CAMPUS_FK]: { code: "NOT_FOUND", message: "La sede no existe." },
  // STU-R6 / D5: a missing guardian person is "not a guardian" too.
  [GUARDIAN_PERSON_FK]: {
    code: "BAD_REQUEST",
    message: "El usuario seleccionado no es un acudiente.",
  },
  // Writer-authored.
  [STUDENT_PERSON_FK]: { code: "NOT_FOUND", message: "El usuario no existe." },
  [GUARDIAN_STUDENT_FK]: { code: "NOT_FOUND", message: "El estudiante no existe." },
  [ENROLLMENT_STUDENT_FK]: { code: "NOT_FOUND", message: "El estudiante no existe." },
  [ENROLLMENT_OFFERING_FK]: { code: "NOT_FOUND", message: "La materia del grado no existe." },
};
const FK_WRITE_FALLBACK: FkWriteRule = {
  code: "BAD_REQUEST",
  message: "Uno de los registros referenciados no existe.",
};

type PgErrorInfo = { code: string; constraint: string | undefined };

/** Finds the driver error: drizzle wraps it, so walk the `cause` chain (bounded). */
function findPgError(error: unknown): PgErrorInfo | null {
  for (let current = error, depth = 0; current && depth < 6; depth += 1) {
    if (typeof current !== "object") return null;
    const { code, constraint } = current as { code?: unknown; constraint?: unknown };
    if (typeof code === "string" && /^(?=.*\d)[0-9A-Z]{5}$/.test(code)) {
      return { code, constraint: typeof constraint === "string" ? constraint : undefined };
    }
    current = (current as { cause?: unknown }).cause;
  }
  return null;
}

/** The mapped error, or `null` when the error is not one this module knows. */
export function mapDbError(
  error: unknown,
  operation: DbOperation,
  options: DbErrorOptions = {},
): ORPCError<string, unknown> | null {
  const pg = findPgError(error);
  if (!pg) return null;
  const constraint = pg.constraint ?? "";

  if (pg.code === SQLSTATE_UNIQUE_VIOLATION) {
    const message = UNIQUE_MESSAGES[constraint];
    return message ? new ORPCError("CONFLICT", { status: CONFLICT_STATUS, message }) : null;
  }

  if (pg.code === SQLSTATE_EXCLUSION_VIOLATION) {
    const message = EXCLUSION_MESSAGES[constraint];
    return message ? new ORPCError("CONFLICT", { status: CONFLICT_STATUS, message }) : null;
  }

  if (pg.code === SQLSTATE_CHECK_VIOLATION) {
    const message = CHECK_MESSAGES[constraint];
    return message ? new ORPCError("BAD_REQUEST", { message }) : null;
  }

  if (operation === "delete") {
    if (pg.code === SQLSTATE_RESTRICT_VIOLATION || pg.code === SQLSTATE_FOREIGN_KEY_VIOLATION) {
      return new ORPCError(HAS_DEPENDENTS, {
        status: CONFLICT_STATUS,
        message:
          options.personRole === undefined
            ? (DEPENDENTS_MESSAGES[constraint] ??
              USER_DEPENDENTS_BY_FK[constraint] ??
              DEPENDENTS_FALLBACK)
            : userDependentsMessage(options.personRole, constraint),
      });
    }
    return null;
  }

  if (pg.code === SQLSTATE_FOREIGN_KEY_VIOLATION) {
    const rule = FK_WRITE_RULES[constraint] ?? FK_WRITE_FALLBACK;
    return new ORPCError(rule.code, { message: rule.message });
  }
  return null;
}

/** Throws the mapped error, or the original error when it is unknown (never swallows). */
export function rethrowDbError(
  error: unknown,
  operation: DbOperation,
  options: DbErrorOptions = {},
): never {
  throw mapDbError(error, operation, options) ?? error;
}
